use placement_cell;
#STUDENT_INFO

CREATE TABLE STUDENT_INFO (
STUDENT_ID BIGINT NOT NULL AUTO_INCREMENT,
ACTIVE_BACKLOG INTEGER,
ADMISSION_YEAR VARCHAR(10),
COLLEGE_NAME VARCHAR(100),
COMPANY_NAME VARCHAR(100),
COURSE VARCHAR(100),
CURRENT_ADDRESS VARCHAR(1000),
DATE_OF_BIRTH TIMESTAMP,
DIVISION VARCHAR(5),
EMAIL VARCHAR(100) NOT NULL,
EXPERIENCE VARCHAR(1),
EXPERIENCE_END_DATE TIMESTAMP,
EXPERIENCE_START_DATE TIMESTAMP,
FIRST_NAME VARCHAR(50),
GAP VARCHAR(5),
GAP_END_DATE TIMESTAMP,
GAP_START_DATE TIMESTAMP,
GENDER VARCHAR(10),
HIGHEST_QUALIFICATION_MARKS FLOAT,
HIGHEST_QUALIFICATION_NAME VARCHAR(100),
HIGHEST_QUALIFICATION_PASSING_YEAR VARCHAR(10),
HSC_MARKS FLOAT,
HSC_PASSING_YEAR VARCHAR(10),
LAST_NAME VARCHAR(50),
MIDDLE_NAME VARCHAR(50),
MOBILE_NUMBER VARCHAR(20) NOT NULL,
OTHER_GRADUATION_MARKS FLOAT,
OTHER_GRADUATION_NAME VARCHAR(100),
OTHER_GRADUATION_PASSING_YEAR VARCHAR(10),
PASSING_YEAR VARCHAR(10),
PERMANENT_ADDRESS VARCHAR(1000),
POSITION VARCHAR(50),
ROLE VARCHAR(50),
ROLL_NUMBER VARCHAR(20) UNIQUE NOT NULL,
SEM_1_SGPA FLOAT,
SEM_2_SGPA FLOAT,
SEM_3_SGPA FLOAT,
SEM_4_SGPA FLOAT,
AGG_CGPA FLOAT,
SEMESTER INTEGER,
SSC_MARKS FLOAT,
SSC_PASSING_YEAR VARCHAR(10),
TOTAL_BACKLOGS INTEGER,
USERNAME VARCHAR(50),
PRIMARY KEY (STUDENT_ID)
);


#ADMIN_INFO

CREATE TABLE ADMIN_INFO
(
	ADMIN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(10),
	FIRST_NAME VARCHAR(50),
	MIDDLE_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	MOBILE_NUMBER VARCHAR(50),
	COURSE VARCHAR(50),
	COLLEGE_NAME VARCHAR(100),
    USERNAME VARCHAR(50)
);


#LOGIN_DETAILS
CREATE TABLE LOGIN_DETAILS
(
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(20),
	IS_ADMIN VARCHAR(1),
	LAST_LOGIN_DATE TIMESTAMP,
	LAST_PASSWORD_RESET TIMESTAMP,
	PASSWORD_EXPIRATION_DATE TIMESTAMP,
	ACCOUNT_STATUS VARCHAR(50)
);

#COMPANY_DETAILS
CREATE TABLE COMPANY_DETAILS
(
	COMPANY_ID INT NOT NULL AUTO_INCREMENT,
	COMPANY_NAME VARCHAR(200),
	ORG_TYPE VARCHAR(100),
	SECTOR VARCHAR(100),
	COMPANY_WEBSITE VARCHAR(100),
	COMPANY_INFO VARCHAR(2000),
	JOB_LOCATION VARCHAR(50),
	ROLE VARCHAR(50),
	PRIMARY KEY (COMPANY_ID)
);

#DRIVE_DETAILS
CREATE TABLE DRIVE_DETAILS
(
	DRIVE_ID INT NOT NULL AUTO_INCREMENT,
	COMPANY_ID INT,
	DRIVE_DATE TIMESTAMP,
	DRIVE_LOCATION VARCHAR(50),
	OFFERED_CTC VARCHAR(50),
	SSC_MARKS FLOAT,
	HSC_MARKS FLOAT,
	GRADUATION_MARKS FLOAT,
	IS_ACTIVE_BACKLOG_ALLOWED VARCHAR(1),
	MAX_ACTIVE_BACKLOG_ALLOWED INT,
	IS_TOTAL_BACKLOG_ALLOWED VARCHAR(1),
	MAX_TOTAL_BACKLOG_ALLOWED INT,
	PRIMARY KEY (DRIVE_ID)
);

#PLACEMENT_STATUS
CREATE TABLE PLACEMENT_STATUS
(
	STUDENT_ID BIGINT,
	DRIVE_ID INT,
	OFFERED_CTC VARCHAR(20),
	HAS_ACCEPTED VARCHAR(1),
	OFFER_RELEASE_DATE TIMESTAMP,
	DATE_OF_JOINING TIMESTAMP
);

#APPLICATION_STATUS
CREATE TABLE APPLICATION_STATUS
(
	APPLICATION_ID BIGINT,
	DRIVE_ID INT,
	STUDENT_ID BIGINT
);