use placement_cell;
#STUDENT_INFO

CREATE TABLE STUDENT_INFO (
STUDENT_ID BIGINT NOT NULL AUTO_INCREMENT,
ACTIVE_BACKLOG INTEGER,
ADMISSION_YEAR VARCHAR(5),
COLLEGE_NAME VARCHAR(100),
COMPANY_NAME VARCHAR(100),
COURSE VARCHAR(100),
CURRENT_ADDRESS VARCHAR(1000),
DATE_OF_BIRTH DATETIME(6),
DIVISION VARCHAR(5),
EMAIL VARCHAR(100) NOT NULL,
EXPERIENCE VARCHAR(5),
EXPERIENCE_END_DATE DATETIME(6),
EXPERIENCE_START_DATE DATETIME(6),
FIRST_NAME VARCHAR(50),
GAP VARCHAR(5),
GAP_END_DATE DATETIME(6),
GAP_START_DATE DATETIME(6),
GENDER VARCHAR(10),
HIGHEST_QUALIFICATION_MARKS VARCHAR(10),
HIGHEST_QUALIFICATION_NAME VARCHAR(100),
HIGHEST_QUALIFICATION_PASSING_YEAR VARCHAR(10),
HSC_MARKS VARCHAR(10),
HSC_PASSING_YEAR VARCHAR(10),
LAST_NAME VARCHAR(50),
MIDDLE_NAME VARCHAR(50),
MOBILE_NUMBER VARCHAR(20) NOT NULL,
OTHER_GRADUATION_MARKS VARCHAR(10),
OTHER_GRADUATION_NAME VARCHAR(100),
OTHER_GRADUATION_PASSING_YEAR VARCHAR(10),
PASSING_YEAR VARCHAR(10),
PERMENENET_ADDRESS VARCHAR(1000),
POSITION VARCHAR(50),
ROLE VARCHAR(50),
ROLL_NUMBER INTEGER NOT NULL,
SEM_1_MARKS INTEGER,
SEM_2_MARKS INTEGER,
SEM_3_MARKS INTEGER,
SEM_4_MARKS INTEGER,
SEMESTER VARCHAR(255),
SSC_MARKS VARCHAR(255),
SSC_PASSING_YEAR VARCHAR(255),
TOTAL_BACKLOGS INTEGER,
USER_NAME VARCHAR(50),
PRIMARY KEY (STUDENT_ID)
);


#ADMIN_INFO

CREATE TABLE ADMIN_INFO
(
	ADMIN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(10),
	FIRST_NAME VARCHAR(50),
	MIDDLE_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	MOBILE_NUMBER VARCHAR(50),
	COURSE VARCHAR(50),
	COLLEGE_NAME VARCHAR(100),
    USERNAME VARCHAR(50)
);


#LOGIN_DETAILS
CREATE TABLE LOGIN_DETAILS
(
	USER_NAME VARCHAR(50),
	PASSWORD VARCHAR(20),
	IS_ADMIN VARCHAR(2),
	LAST_LOGIN_DATE TIMESTAMP,
	LAST_PASSWORD_RESET TIMESTAMP,
	PASSWORD_EXPIRATION_DATE TIMESTAMP,
	ACCOUNT_STATUS VARCHAR(50)
);

#COMPANY_DETAILS
CREATE TABLE COMPANY_DETAILS
(
	COMPANY_ID INT NOT NULL AUTO_INCREMENT,
	COMPANY_NAME VARCHAR(200),
	ORG_TYPE VARCHAR(100),
	SECTOR VARCHAR(100),
	COMPANY_WEBSITE VARCHAR(100),
	COMPANY_INFO VARCHAR(2000),
	JOB_LOCATION VARCHAR(50),
	ROLE VARCHAR(50),
	PRIMARY KEY (COMPANY_ID)
);

#DRIVE_DETAILS
CREATE TABLE DRIVE_DETAILS
(
	DRIVE_ID INT NOT NULL AUTO_INCREMENT,
	COMPANY_ID INT,
	DRIVE_DATE VARCHAR(20),
	DRIVE_LOCATION VARCHAR(200),
	OFFERED_CTC VARCHAR(50),
	SSC_MARKS DECIMAL(4,2),
	HSC_MARKS DECIMAL(4,2),
	GRADUATION_MARKS DECIMAL(4,2),
	ACTIVE_BACKLOG_STATUS VARCHAR(20),
	MAX_ACTIVE_BACKLOG_ALLOWED INT,
	HISTORICAL_BACKLOG_STATUS VARCHAR(20),
	MAX_HIST_BACKLOG_ALLOWED INT,
	PRIMARY KEY (DRIVE_ID)
);

#DRIVE_STATUS
CREATE TABLE DRIVE_STATUS
(
	DRIVE_ID INT,
	COMPANY_ID INT,
	DRIVE_STATUS VARCHAR(50)
);

#PLACEMENT_STATUS
CREATE TABLE PLACEMENT_STATUS
(
	DRIVE_ID INT,
	COMPANY_ID INT,
	STUDENT_ID INT,
	STATUS VARCHAR(20),
	DATE_OF_PLACEMENT VARCHAR(20),
	OFFERED_CTC VARCHAR(20)
);
