use placement_cell;
#STUDENT_INFO
CREATE TABLE STUDENT_INFO
(
	STUDENT_ID INT NOT NULL AUTO_INCREMENT,
	ROLL_NUMBER VARCHAR(20) UNIQUE NOT NULL,
	FIRST_NAME VARCHAR(50),
	MIDDLE_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	DATE_OF_BIRTH VARCHAR(50),
	GENDER VARCHAR(10),
	MOBILE_NUMBER VARCHAR(20) UNIQUE NOT NULL,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	CURRENT_ADDRESS VARCHAR(1000),
	PERMANENT_ADDRESS VARCHAR(1000),
	COURSE VARCHAR(50),
	ADMISSION_YEAR VARCHAR(20),
	PASSING_YEAR VARCHAR(20),
	SEMESTER VARCHAR(10),
	DIVISION VARCHAR(5),
	COLLEGE_NAME VARCHAR(100),
	SSC_PASSING_YEAR VARCHAR(5),
	SSC_MARKS DECIMAL(4,2),
	HSC_PASSING_YEAR INT,
	HSC_MARKS DECIMAL(4,2),
	HIGHEST_QUALIFICATION_NAME VARCHAR(50),
	HIGHEST_QUALIFICATION_PASSING_YEAR VARCHAR(20),
	HIGHEST_QUALIFICATION_MARKS DECIMAL(4,2),
	OTHER_GRADUATION_NAME VARCHAR(50),
	OTHER_GRADUATION_PASSING_YEAR VARCHAR(20),
	OTHER_GRADUATION_MARKS DECIMAL(4,2),
	GAP VARCHAR(5) NOT NULL,
	GAP_START_DURATION TIMESTAMP,
	GAP_END_DURATION TIMESTAMP,
	SEM_1_MARKS DECIMAL(4,2),
	SEM_2_MARKS DECIMAL(4,2),
	SEM_3_MARKS DECIMAL(4,2),
	SEM_4_MARKS DECIMAL(4,2),
	ACTIVE_BACKLOG INT,
	TOTAL_BACKLOGS INT,
	EXPERIENCE VARCHAR(5),
	EXPERIENCE_START_DATE TIMESTAMP,
	EXPERIENCE_END_DATE TIMESTAMP,
	COMPANY_NAME VARCHAR(100),
	POSITION VARCHAR(50),
	ROLE VARCHAR(50),
	PRIMARY KEY (STUDENT_ID)
);


#ADMIN_INFO

CREATE TABLE ADMIN_INFO
(
	ADMIN_ID INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(10),
	FIRST_NAME VARCHAR(50),
	MIDDLE_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	MOBILE_NUMBER VARCHAR(50),
	COURSE VARCHAR(50),
	COLLEGE_NAME VARCHAR(100),
	PRIMARY KEY (ADMIN_ID)
);

#COMPANY_DETAILS
CREATE TABLE COMPANY_DETAILS
(
	COMPANY_ID INT NOT NULL AUTO_INCREMENT,
	COMPANY_NAME VARCHAR(200),
	ORG_TYPE VARCHAR(100),
	SECTOR VARCHAR(100),
	COMPANY_WEBSITE VARCHAR(100),
	COMPANY_INFO VARCHAR(2000),
	JOB_LOCATION VARCHAR(50),
	ROLE VARCHAR(50),
	PRIMARY KEY (COMPANY_ID)
);

#DRIVE_DETAILS
CREATE TABLE DRIVE_DETAILS
(
	DRIVE_ID INT NOT NULL AUTO_INCREMENT,
	COMPANY_ID INT,
	DRIVE_DATE VARCHAR(20),
	DRIVE_LOCATION VARCHAR(200),
	OFFERED_CTC VARCHAR(50),
	SSC_MARKS DECIMAL(4,2),
	HSC_MARKS DECIMAL(4,2),
	GRADUATION_MARKS DECIMAL(4,2),
	ACTIVE_BACKLOG_STATUS VARCHAR(20),
	MAX_ACTIVE_BACKLOG_ALLOWED INT,
	HISTORICAL_BACKLOG_STATUS VARCHAR(20),
	MAX_HIST_BACKLOG_ALLOWED INT,
	PRIMARY KEY (DRIVE_ID)
);

#DRIVE_STATUS
CREATE TABLE DRIVE_STATUS
(
	DRIVE_ID INT,
	COMPANY_ID INT,
	ELIGIBLE_STUDENT_ID INT,
	APPLICATION_STATUS VARCHAR(50)
);

#PLACEMENT_STATUS
CREATE TABLE PLACEMENT_STATUS
(
	DRIVE_ID INT,
	COMPANY_ID INT,
	APPLIED_STUDENT_ID INT,
	APPLICATION_STATUS VARCHAR(20),
	DATE_OF_PLACEMENT VARCHAR(20),
	OFFERED_CTC VARCHAR(20)
);

#LOGIN_DETAILS
CREATE TABLE LOGIN_DETAILS
(
	LOGIN_ID INT,
	PASSWORD VARCHAR(20),
	IS_ADMIN VARCHAR(2),
	LAST_LOGIN_DATE TIMESTAMP,
	LAST_PASSWORD_RESET TIMESTAMP,
	PASSWORD_EXPIRATION_DATE TIMESTAMP,
	ACCOUNT_STATUS VARCHAR(50)
);